import { dbQuery } from "../db/postgres";
import { getBaddyAccessToken, refreshBaddyAccessToken } from "./baddy-auth";

export type Platform = "baddy" | "wekkuk" | "sponet" | "facecock";
type RecordItem = { title: string; sourceId: string; startDate: string | null; endDate?: string | null; venue?: string; region?: string; organizer?: string; supervisor?: string; sponsor?: string; description?: string; posterUrl?: string; posterUrls?: string[]; officialUrl?: string; sourceUrl?: string; metadata?: Record<string, unknown>; excluded?: boolean };
export type CollectorLog = { id: string; platform: Platform; status: "success" | "partial" | "failed"; startedAt: string; durationMs: number; added: number; updated: number; unchanged: number; message: string; changes: { title: string; kind: "added" | "updated"; fields: string[] }[] };
const WEKKUK_EXCLUDED_TITLE_PARTS = ["배드민턴 유청소년", "배드민턴 시니어", "배드민턴 성인부"];
const isExcludedWekkukTitle = (title: string) => WEKKUK_EXCLUDED_TITLE_PARTS.some(part => title.includes(part));
const logs: CollectorLog[] = [];
export function getCollectorLogs(platform?: string) { return platform && platform !== "all" ? logs.filter(x => x.platform === platform) : logs; }
function parseDate(value: string) { const m = value.match(/(20\d{2})[^\d]+(\d{1,2})[^\d]+(\d{1,2})/); return m ? `${m[1]}-${m[2].padStart(2, "0")}-${m[3].padStart(2, "0")}` : null; }
function parseFacecockPeriod(value: string) { const start = parseDate(value); if (!start) return { startDate: null, endDate: null }; const [year, month] = start.split("-"); const fullDates = [...value.matchAll(/(20\d{2})[^\d]+(\d{1,2})[^\d]+(\d{1,2})/g)]; if (fullDates.length > 1) return { startDate: start, endDate: `${fullDates[1][1]}-${fullDates[1][2].padStart(2, "0")}-${fullDates[1][3].padStart(2, "0")}` }; const shortEnd = value.match(/(?:~|～|\-)[^\d]*(\d{1,2})일/); return { startDate: start, endDate: shortEnd ? `${year}-${month}-${shortEnd[1].padStart(2, "0")}` : start }; }
async function fetchText(url: string, headers: Record<string, string> = {}) { const r = await fetch(url, { headers, signal: AbortSignal.timeout(15000) }); if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.text(); }
function decodeHtml(value: string) { return value.replace(/&nbsp;/gi, " ").replace(/&amp;/gi, "&").replace(/&lt;/gi, "<").replace(/&gt;/gi, ">").replace(/&quot;/gi, '"').replace(/&#(?:0*39|x0*27);/gi, "'").replace(/&#(\d+);/g, (_, n) => String.fromCharCode(Number(n))).replace(/&#x([0-9a-f]+);/gi, (_, n) => String.fromCharCode(parseInt(n, 16))); }
function htmlText(value: string, multiline = false) { const normalized = multiline ? value.replace(/<br\s*\/?\s*>/gi, "\n").replace(/<\/p>/gi, "\n") : value; return decodeHtml(normalized.replace(/<[^>]+>/g, " ")).replace(multiline ? /[ \t]+/g : /\s+/g, " ").replace(/\n\s+/g, "\n").trim(); }
function wekkukField(html: string, label: string) { const escaped = label.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); return html.match(new RegExp(`<div class=["']gm-stem["'][^>]*>[\\s\\S]*?<p class=["']gm-item["'][^>]*>\\s*${escaped}[\\s\\S]*?<div class=["']gm-text["'][^>]*>([\\s\\S]*?)<\\/div>\\s*<\\/div>`, "i"))?.[1] || ""; }
function facecockField(html: string, label: string) { const escaped = label.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); return htmlText(html.match(new RegExp(`<th[^>]*>\\s*${escaped}\\s*<\\/th>\\s*<td[^>]*>([\\s\\S]*?)<\\/td>`, "i"))?.[1] || ""); }
function facecockNotice(html: string) { const marker = '<div class="contents-box">'; const start = html.indexOf(marker); if (start < 0) return ""; const end = html.indexOf('<div class="margin-bottom-', start + marker.length); const block = html.slice(start + marker.length, end > start ? end : undefined).replace(/<script[\s\S]*?<\/script>/gi, "").replace(/<style[\s\S]*?<\/style>/gi, "").replace(/<br\s*\/?\s*>/gi, "\n").replace(/<\/(?:p|div|tr|h[1-6]|li)>/gi, "\n").replace(/<\/td>/gi, "\t"); return decodeHtml(block.replace(/<[^>]+>/g, " ")).replace(/\r/g, "").replace(/[ \t]+\n/g, "\n").replace(/\n[ \t]+/g, "\n").replace(/\n{3,}/g, "\n\n").replace(/[ \t]{2,}/g, " ").trim().slice(0, 30000); }
async function mapConcurrent<T, R>(items: T[], concurrency: number, task: (item: T) => Promise<R>) { const results = new Array<R>(items.length); let next = 0; await Promise.all(Array.from({ length: Math.min(concurrency, items.length) }, async () => { while (next < items.length) { const index = next++; results[index] = await task(items[index]); } })); return results; }
async function enrichWekkuk(item: RecordItem): Promise<RecordItem> { try { const sourceUrl = `https://app2.wekkuk.com/v2/contest_badminton/contest/${item.sourceId}`; const html = await fetchText(sourceUrl); const venue = htmlText(wekkukField(html, "대회장소")); const organizer = htmlText(wekkukField(html, "주최")) || item.organizer; const supervisor = htmlText(wekkukField(html, "주관")); const sponsor = htmlText(wekkukField(html, "후원")); const description = htmlText(wekkukField(html, "안내"), true); const officialBlock = wekkukField(html, "대회요강"); const officialUrl = officialBlock.match(/action_app_link\(["']([^"']+)/i)?.[1]; const posterUrl = html.match(/https:\/\/upload\.wekkuk\.com\/contest_badminton_poster\/[^"'<>\s]+/i)?.[0]; return { ...item, venue, organizer, supervisor, sponsor, description, officialUrl: officialUrl ? decodeHtml(officialUrl) : undefined, posterUrl, sourceUrl }; } catch { return item; } }

async function enrichSponet(item: RecordItem): Promise<RecordItem> { try { const response = await fetch(`https://sponet.net/api/v1/tournaments/${encodeURIComponent(item.sourceId)}/detail`, { signal: AbortSignal.timeout(15000) }); if (!response.ok) return item; const json = await response.json() as any; const x = json?.data; if (!x) return item; const dates = String(x.date || "").match(/20\d{2}[^\d]+\d{1,2}[^\d]+\d{1,2}/g) || []; const posterUrls = Array.isArray(x.posterUrls) ? x.posterUrls.filter((url: unknown): url is string => typeof url === "string" && Boolean(url)) : []; return { ...item, title: x.title || item.title, startDate: parseDate(dates[0] || x.date || "") || item.startDate, endDate: parseDate(dates[1] || "") || parseDate(dates[0] || x.date || "") || item.startDate, venue: x.location || item.venue, organizer: x.host || "", supervisor: x.organizer || "", sponsor: x.sponsor || "", description: x.content || "", officialUrl: x.outlineFileUrl || undefined, posterUrls, posterUrl: posterUrls[0] || item.posterUrl, metadata: { cosponsor: x.cosponsor || "", homepage: x.homepage || "", managerName: x.managerName || "", managerEmail: x.managerEmail || "", managerPhone: x.managerPhone || "", registrationPeriod: x.registrationPeriod || "", isApplySponet: Boolean(x.isApplySponet), isEnterReg: Boolean(x.isEnterReg), matchOpenYn: x.match_open_yn || "", entryOpenYn: x.entry_open_yn || "", escoreUseYn: x.escoreUseYn || "" } }; } catch { return item; } }

async function enrichFacecock(item: RecordItem): Promise<RecordItem> { try { const sourceUrl = `https://www.facecock.co.kr/page/index.php?pid=game_view&ga_id=${item.sourceId}`; const html = await fetchText(sourceUrl); const period = parseFacecockPeriod(facecockField(html, "대회기간")); const homepageMatch = html.match(/<th[^>]*>\s*홈페이지\s*<\/th>\s*<td[^>]*>[\s\S]*?<a href=["']([^"']+)/i); const homepage = homepageMatch?.[1] && !/^https?:\/\/?$/i.test(homepageMatch[1]) ? decodeHtml(homepageMatch[1]) : ""; const posterPath = html.match(/<img src=["']([^"']*\/data\/game\/[^"']+)/i)?.[1]; const officialUrl = html.includes(`game_pdf.html?wr_id=${item.sourceId}`) ? `https://facecock.co.kr/app/game_pdf.html?wr_id=${item.sourceId}` : undefined; const base = "https://www.facecock.co.kr/page/index.php"; return { ...item, startDate: period.startDate || item.startDate, endDate: period.endDate || item.endDate || item.startDate, venue: facecockField(html, "대회장소") || item.venue, region: facecockField(html, "대회지역") || item.region, description: facecockNotice(html), posterUrl: posterPath ? new URL(decodeHtml(posterPath), "https://www.facecock.co.kr").toString() : item.posterUrl, officialUrl, sourceUrl, metadata: { participantRegion: facecockField(html, "참가지역"), registrationPeriod: facecockField(html, "접수기간"), registrationContact: facecockField(html, "접수문의"), homepage, followers: facecockField(html, "팔로워"), registrationUrl: `${base}?pid=game_regist&ga_id=${item.sourceId}`, scheduleUrl: `${base}?pid=game_schedule&ga_id=${item.sourceId}`, liveUrl: `${base}?pid=game_ing&ga_id=${item.sourceId}`, courtUrl: `${base}?pid=game_court&ga_id=${item.sourceId}`, resultUrl: `${base}?pid=game_result&ga_id=${item.sourceId}` } }; } catch { return item; } }

async function fetchRecords(platform: Platform): Promise<RecordItem[]> {
  if (platform === "sponet") { const now = new Date(); const today = now.toLocaleDateString("en-CA", { timeZone: "Asia/Seoul" }); const supportedMonths = (11 - now.getMonth()) + 13; const monthsAhead = Math.max(1, Number(process.env.SPONET_MONTHS_AHEAD || supportedMonths)); const records: RecordItem[] = []; monthLoop: for (let offset = 0; offset < monthsAhead; offset++) { const target = new Date(now.getFullYear(), now.getMonth() + offset, 1); let page = 1; let hasMore = true; while (hasMore) { const response = await fetch(`https://sponet.net/api/v1/tournaments/by-month?year=${target.getFullYear()}&month=${target.getMonth() + 1}&page=${page}&limit=100`, { signal: AbortSignal.timeout(15000) }); if (response.status === 400) break monthLoop; if (!response.ok) throw new Error(`Sponet HTTP ${response.status}`); const json = await response.json() as any; for (const x of json?.data?.data || []) { const startDate = parseDate(x.date || ""); if (startDate && startDate > today) records.push({ title: x.title, sourceId: String(x.id), startDate, venue: x.location || "", posterUrl: x.imageUrl || undefined, sourceUrl: x.detailUrl || x.url }); } hasMore = Boolean(json?.data?.pagination?.hasMore); page++; } } const unique = [...new Map(records.map(x => [x.sourceId, x])).values()]; return mapConcurrent(unique, 6, enrichSponet); }
  if (platform === "wekkuk") { const first = await fetchText("https://app2.wekkuk.com/v2/contest_badminton/contest?page=1"); const last = Number(first.match(/pg_last[\s\S]{0,250}?toPage\('([0-9]+)'/)?.[1] || 1); const pages = [first, ...await Promise.all(Array.from({length: Math.max(last - 1, 0)}, (_, i) => fetchText(`https://app2.wekkuk.com/v2/contest_badminton/contest?page=${i + 2}`)))]; const pattern = /goto_contest_view\((\d+),\s*[\"']([^\"']+)[\"'][\s\S]{0,600}?gm-name[^>]*>([^<]*)[\s\S]{0,1200}?gm-time[^>]*>([^<]+)/g; const seen = new Set<string>(); const records: RecordItem[] = pages.flatMap(h => [...h.matchAll(pattern)].map(x => { const organizer = htmlText(x[3]).replace(/^\(|\)$/g, "").trim(); return { title: x[2].trim(), sourceId: x[1], organizer, excluded: organizer === "대한체육회", startDate: parseDate(x[4]), sourceUrl: `https://app2.wekkuk.com/v2/contest_badminton/contest/${x[1]}` }; }).filter(x => !seen.has(x.sourceId) && seen.add(x.sourceId))); const today = new Date().toLocaleDateString("en-CA", { timeZone: "Asia/Seoul" }); const upcoming = records.filter(x => !x.excluded && x.startDate && x.startDate >= today); const enriched = await mapConcurrent(upcoming, 6, enrichWekkuk); const details = new Map(enriched.map(x => [x.sourceId, x])); return records.map(x => details.get(x.sourceId) || x); }
  if (platform === "facecock") { const first = await fetchText("https://www.facecock.co.kr/page/?pid=game"); const pageNumbers = [...first.matchAll(/(?:&amp;|&)page=(\d+)/g)].map(x => Number(x[1])); const lastPage = Math.max(1, ...pageNumbers); const pages = [first, ...await Promise.all(Array.from({ length: Math.max(lastPage - 1, 0) }, (_, index) => fetchText(`https://www.facecock.co.kr/page/index.php?pid=game&page=${index + 2}`)))]; const pattern = /<div class=["']multi-item["'][\s\S]*?<img src=["']([^"']+)["'][\s\S]*?game_view(?:&amp;|&)ga_id=(\d+)[^>]*>[\s\S]*?<strong>([\s\S]*?)<\/strong>[\s\S]*?<p class=["']multi-cont["']>([\s\S]*?)<\/p>/g; const records = pages.flatMap(h => [...h.matchAll(pattern)].map(x => { const summary = htmlText(x[4], true); const period = parseFacecockPeriod(summary); const region = summary.match(/^\[([^\]]+)\]/)?.[1] || ""; const posterUrl = new URL(decodeHtml(x[1]), "https://www.facecock.co.kr").toString(); return { title: htmlText(x[3]), sourceId: x[2], startDate: period.startDate, endDate: period.endDate, region, posterUrl, sourceUrl: `https://www.facecock.co.kr/page/index.php?pid=game_view&ga_id=${x[2]}` }; }).filter(x => x.title && x.startDate)); const unique = [...new Map(records.map(x => [x.sourceId, x])).values()]; return mapConcurrent(unique, 6, enrichFacecock); }
  const requestBaddyList = async (token: string) => {
    const response = await fetch("http://real.badmintonfriends.co.kr:8080/comp/list", { headers: { Authorization: `Bearer ${token}`, Cookie: `BADDY_TOKEN=${token}; aToken=${token}`, accept: "application/json", "user-agent": "Dart/3.6 (dart:io)" }, signal: AbortSignal.timeout(15000) });
    const text = await response.text();
    let body: any; try { body = JSON.parse(text); } catch { body = null; }
    return { response, body, text };
  };
  let result = await requestBaddyList(await getBaddyAccessToken());
  if (!result.response.ok || (result.body?.resCode && result.body.resCode !== "001")) result = await requestBaddyList(await refreshBaddyAccessToken());
  if (!result.response.ok) throw new Error(`Baddy HTTP ${result.response.status}`);
  const j = result.body || JSON.parse(result.text); if (j?.resCode && j.resCode !== "001") throw new Error(j.msg || `Baddy API resCode ${j.resCode}`);
  return (j?.result?.compInfoList || []).map((x: any) => ({ title: x.TITLE, sourceId: String(x.PK), startDate: parseDate(x.COMP_ING_TIME_LIST?.[0] || ""), venue: (x.GYM_INFO_LIST || []).map((g: any) => g.NAME).filter(Boolean).join(" / "), posterUrl: x.IMG_COMP_POST_INFO?.URL, officialUrl: x.OFFICAL_FILE_VIEWER_URL, sourceUrl: `https://badmintonfriends.page.link/toNamed?pageName=/CompetitionDetailsHomePage&pk=${x.PK}` }));
}

async function persistRecords(platform: Platform, records: RecordItem[]) { let added = 0, updated = 0; const changes: CollectorLog["changes"] = [];
  if (platform === "wekkuk") for (const record of records) if (isExcludedWekkukTitle(record.title)) record.excluded = true;
  for (const r of records) { const found = await dbQuery<{ id: string }>("SELECT c.id FROM competitions c JOIN competition_sources s ON s.competition_id=c.id WHERE s.platform=$1 AND s.source_id=$2", [platform, r.sourceId]); if (r.excluded) { if (found.rowCount) await dbQuery("DELETE FROM competitions WHERE id=$1", [found.rows[0].id]); continue; } if (!r.title || !r.startDate) continue; let id: string;
    if (found.rowCount) { id = found.rows[0].id; await dbQuery("UPDATE competitions SET title=$1,venue=$2,region=$3,start_date=$4,end_date=$5,description=$6,organizer=$7,supervisor=$8,sponsor=$9,platform_metadata=$10,updated_at=now() WHERE id=$11", [r.title, r.venue || "", r.region || "", r.startDate, r.endDate || r.startDate, r.description || null, r.organizer || null, r.supervisor || null, r.sponsor || null, JSON.stringify(r.metadata || {}), id]); await dbQuery("UPDATE competition_sources SET source_url=$1,last_crawled_at=now() WHERE competition_id=$2 AND platform=$3 AND source_id=$4", [r.sourceUrl || null, id, platform, r.sourceId]); updated++; changes.push({ title: r.title, kind: "updated", fields: ["competition details"] }); }
    else { const ins = await dbQuery<{ id: string }>("INSERT INTO competitions(title,venue,region,start_date,end_date,description,organizer,supervisor,sponsor,platform_metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id", [r.title, r.venue || "", r.region || "", r.startDate, r.endDate || r.startDate, r.description || null, r.organizer || null, r.supervisor || null, r.sponsor || null, JSON.stringify(r.metadata || {})]); id = ins.rows[0].id; await dbQuery("INSERT INTO competition_sources(competition_id,platform,source_id,source_url,last_crawled_at) VALUES($1,$2,$3,$4,now())", [id, platform, r.sourceId, r.sourceUrl || null]); added++; changes.push({ title: r.title, kind: "added", fields: ["competition"] }); }
    const posterUrls = r.posterUrls?.length ? r.posterUrls : r.posterUrl ? [r.posterUrl] : []; if (posterUrls.length) { await dbQuery("DELETE FROM competition_images WHERE competition_id=$1 AND kind='poster'", [id]); for (const url of posterUrls) await dbQuery("INSERT INTO competition_images(competition_id,kind,image_url,alt_text) VALUES($1,'poster',$2,$3)", [id, url, r.title]); }
    if (r.officialUrl) { await dbQuery("DELETE FROM competition_documents WHERE competition_id=$1 AND name='official'", [id]); await dbQuery("INSERT INTO competition_documents(competition_id,name,file_url,content_type) VALUES($1,'official',$2,$3)", [id, r.officialUrl, r.officialUrl.toLowerCase().includes(".pdf") ? "application/pdf" : "text/html"]); }
  } return { added, updated, unchanged: Math.max(records.length - added - updated, 0), changes };
}
async function persistLog(log: CollectorLog) { try { await dbQuery("INSERT INTO collector_logs(platform,status,started_at,finished_at,duration_ms,added_count,updated_count,unchanged_count,message,changes) VALUES($1,$2,$3,now(),$4,$5,$6,$7,$8,$9)", [log.platform, log.status, log.startedAt, log.durationMs, log.added, log.updated, log.unchanged, log.message, JSON.stringify(log.changes)]); } catch {} }
export async function runCollector(platform: Platform): Promise<CollectorLog> { const started = Date.now(); try { const records = await fetchRecords(platform); const result = await persistRecords(platform, records); const log = { id: `run-${Date.now()}`, platform, status: records.length ? "success" : "partial", startedAt: new Date().toISOString(), durationMs: Date.now() - started, ...result, message: `${records.length} records collected`, changes: result.changes } as CollectorLog; logs.unshift(log); await persistLog(log); return log; } catch (e) { const log = { id: `run-${Date.now()}`, platform, status: "failed", startedAt: new Date().toISOString(), durationMs: Date.now() - started, added: 0, updated: 0, unchanged: 0, message: e instanceof Error ? e.message : "collection failed", changes: [] } as CollectorLog; logs.unshift(log); await persistLog(log); return log; } }
