import { NextResponse } from "next/server";
import { isAdmin } from "../../../../lib/admin";
import { getCollectorSettings, updateCollectorSettings } from "../../../../lib/collector-settings";
import { dbQuery } from "../../../../db/postgres";

const columns = ["baddyEnabled", "wekkukEnabled", "sponetEnabled", "facecockEnabled"] as const;
const sqlColumns = { baddyEnabled: "baddy_enabled", wekkukEnabled: "wekkuk_enabled", sponetEnabled: "sponet_enabled", facecockEnabled: "facecock_enabled" };
export async function GET(request: Request) { if (!isAdmin(request)) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); try { const result = await dbQuery(`SELECT interval_hours AS "intervalHours", enabled, baddy_enabled AS "baddyEnabled", wekkuk_enabled AS "wekkukEnabled", sponet_enabled AS "sponetEnabled", facecock_enabled AS "facecockEnabled" FROM collector_settings WHERE id = true`); return NextResponse.json({ data: result.rows[0] || { intervalHours: 6, enabled: true, baddyEnabled: true, wekkukEnabled: true, sponetEnabled: true, facecockEnabled: true }, source: "postgres" }); } catch { return NextResponse.json({ data: getCollectorSettings(), source: "memory" }); } }
export async function PUT(request: Request) { if (!isAdmin(request)) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const body = await request.json() as Record<string, unknown>; const intervalHours = Number(body.intervalHours || 6); if (![1, 6, 12, 24].includes(intervalHours)) return NextResponse.json({ error: "Invalid interval" }, { status: 400 }); const values = columns.map((column) => body[column] !== false); try { const result = await dbQuery(`INSERT INTO collector_settings (id, interval_hours, enabled, baddy_enabled, wekkuk_enabled, sponet_enabled, facecock_enabled, updated_at) VALUES (true,$1,$2,$3,$4,$5,$6,now()) ON CONFLICT (id) DO UPDATE SET interval_hours=EXCLUDED.interval_hours, enabled=EXCLUDED.enabled, baddy_enabled=EXCLUDED.baddy_enabled, wekkuk_enabled=EXCLUDED.wekkuk_enabled, sponet_enabled=EXCLUDED.sponet_enabled, facecock_enabled=EXCLUDED.facecock_enabled, updated_at=now() RETURNING interval_hours AS "intervalHours", enabled, baddy_enabled AS "baddyEnabled", wekkuk_enabled AS "wekkukEnabled", sponet_enabled AS "sponetEnabled", facecock_enabled AS "facecockEnabled"`, [intervalHours, body.enabled !== false, ...values]); return NextResponse.json({ data: result.rows[0], source: "postgres" }); } catch { return NextResponse.json({ data: updateCollectorSettings({ intervalHours, enabled: body.enabled !== false }), source: "memory" }); } }
